### ISSUE TITLE
Which do you recommend using, openapi-for-go or authlete-go?

### ISSUE THREAD

**Issue by haton14** [authlete/authlete-go#15]
Should we consider switching to using openapi-for-go in the future?
Not only does it seem like its main branch is being actively maintained, but there also exists v3 branch. 
I am asking this question primarily because it appears that "authlete-go" is not being maintained as regularly.

**Comment by hefa** [comment]
It is worth considering.

openapi-for-go is autogenerated from our OpenAPI spec, so it will always be more up to date. It is also the client library that we use internally (e.g. in the terraform provider), so we need to keep it updated.

Unfortunately we don't have the resources to always keep all of our hand-written client libraries up to date with the latest API changes, but authlete-go will also be updated to support v3 at the latest during Q2.

**Comment by haton14** [comment]
I'm so happy this great project will continue.
